### ISSUE TITLE
Use with React-Native

### ISSUE THREAD

**Issue by cuongtora1996** [luggage66/jsx-xsl-fo#3]
I face that the issue to generate the pdf with custom layout and I want to use this library. Can it use with React Native Webview to generate PDF.

**Comment by luggage66** [comment]
Maybe with more work. This library just outputs xml that you then must feed through Apache FOP to make the PDF. I don't make a PDF directly. But that PDF should then be view-able in a WebView. FOP may run slowly on a phone to make large PDFs.

Do you need some of the specific layout that FO does? Or can you get away with just normal HTML?

**Comment by cuongtora1996** [comment]
Late thanks. I will try to figure it out.

**Comment by luggage66** [comment]
Closing this old issue. I think the question has been answered.
